//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistrationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public System.Guid ID { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Cc { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<System.DateTime> SendToDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int AutoID { get; set; }
    }
}
